rule detect_convergence:
    """Detect convergent amino acid substitutions from ancestral reconstruction.

    Requires IQ-TREE to have been run with --ancestral to produce the .state file.
    The .state file is generated by the phylogeny rule (iqtree2 --ancestral flag).
    """
    input:
        alignment="results/alignments/{family}.trimmed.fa",
        tree="results/phylogenies/{family}.rooted.treefile",
        state="results/phylogenies/{family}.state",
        species_yaml="config/species.yaml",
    output:
        tsv="results/convergence/{family}.convergent_sites.tsv",
    params:
        threshold=config["convergence"]["posterior_threshold"],
        min_lineages=config["convergence"]["min_lineages"],
    conda:
        "../envs/bioinfo.yaml"
    log:
        "logs/convergence/{family}.log",
    threads: 1
    shell:
        """
        python workflow/scripts/detect_convergence.py \
            --alignment {input.alignment} \
            --tree {input.tree} \
            --state {input.state} \
            --species-yaml {input.species_yaml} \
            --output {output.tsv} \
            --family {wildcards.family} \
            --threshold {params.threshold} \
            --min-lineages {params.min_lineages} \
            --verbose \
            2> {log}
        """
